version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kentork/hi
    steps:
      - checkout
      - run: go get github.com/martinlindhe/notify
      - run: go get github.com/urfave/cli
      - run: bo build
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kentork/hi
    steps:
      - checkout
      - run: go get github.com/martinlindhe/notify
      - run: go get github.com/urfave/cli
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: gox -output "/go/pkg/{{.Dir}}_{{.OS}}_{{.Arch}}"  ./ ./...
      - run: ghr -u $CIRCLE_PROJECT_USERNAME $CIRCLE_TAG /go/pkg/
